version: "3.9"
networks:
  default:
    driver: bridge
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
        
services:
  app:
    build: .
    container_name: feniks_ato
    command: streamlit run app.py
    restart: always
    networks:
      - t2_proxy
    # ports: # Disable specification when deploying in production
    #   - 88:8501 #  Disable specification when deploying in production
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.feniks_ato-rtr.entrypoints=https"
      - "traefik.http.routers.feniks_ato-rtr.rule=Host(`feniks_ato.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.feniks_ato-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.feniks_ato-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.feniks_ato-rtr.service=feniks_ato-svc"
      - "traefik.http.services.feniks_ato-svc.loadbalancer.server.port=8501" # 3001 is default port for streamlit